export type GameSessionStatus = "completed" | "active" | "cancelled";

export type MockGameSession = {
  id: string;
  restaurantName: string;
  restaurantId: string;
  date: string;
  time: string;
  mode: string;
  activeTables: number;
  tablePrice: number;
  grossRevenue: number;
  commissionPercent: number;
  restaurantCommission: number;
  prizeAmount: number;
  hosterLiveRevenue: number;
  winnerFolio: string;
  status: GameSessionStatus;
  durationMinutes: number;
};

export const mockGameSessions: MockGameSession[] = [
  {
    id: "session-001",
    restaurantName: "Doroteo",
    restaurantId: "doroteo",
    date: "2026-05-21",
    time: "22:48",
    mode: "Figura X",
    activeTables: 50,
    tablePrice: 200,
    grossRevenue: 10000,
    commissionPercent: 25,
    restaurantCommission: 2500,
    prizeAmount: 6500,
    hosterLiveRevenue: 1000,
    winnerFolio: "HL-041",
    status: "completed",
    durationMinutes: 18,
  },
  {
    id: "session-002",
    restaurantName: "Rancho Viejo",
    restaurantId: "rancho-viejo",
    date: "2026-05-21",
    time: "22:16",
    mode: "4 esquinas",
    activeTables: 50,
    tablePrice: 150,
    grossRevenue: 7500,
    commissionPercent: 20,
    restaurantCommission: 1500,
    prizeAmount: 5200,
    hosterLiveRevenue: 800,
    winnerFolio: "HL-028",
    status: "completed",
    durationMinutes: 14,
  },
  {
    id: "session-003",
    restaurantName: "Terraza 88",
    restaurantId: "terraza-88",
    date: "2026-05-21",
    time: "21:42",
    mode: "Centro 4",
    activeTables: 30,
    tablePrice: 200,
    grossRevenue: 6000,
    commissionPercent: 22,
    restaurantCommission: 1320,
    prizeAmount: 4080,
    hosterLiveRevenue: 600,
    winnerFolio: "HL-013",
    status: "completed",
    durationMinutes: 12,
  },
  {
    id: "session-004",
    restaurantName: "Casa Norte",
    restaurantId: "casa-norte",
    date: "2026-05-21",
    time: "21:05",
    mode: "Figura X",
    activeTables: 40,
    tablePrice: 150,
    grossRevenue: 6000,
    commissionPercent: 24,
    restaurantCommission: 1440,
    prizeAmount: 3960,
    hosterLiveRevenue: 600,
    winnerFolio: "HL-036",
    status: "completed",
    durationMinutes: 16,
  },
  {
    id: "session-005",
    restaurantName: "Salon Aurora",
    restaurantId: "salon-aurora",
    date: "2026-05-21",
    time: "20:31",
    mode: "4 esquinas",
    activeTables: 20,
    tablePrice: 150,
    grossRevenue: 3000,
    commissionPercent: 18,
    restaurantCommission: 540,
    prizeAmount: 2160,
    hosterLiveRevenue: 300,
    winnerFolio: "HL-009",
    status: "completed",
    durationMinutes: 10,
  },
  {
    id: "session-006",
    restaurantName: "Doroteo",
    restaurantId: "doroteo",
    date: "2026-05-21",
    time: "23:20",
    mode: "4 esquinas",
    activeTables: 50,
    tablePrice: 300,
    grossRevenue: 15000,
    commissionPercent: 25,
    restaurantCommission: 3750,
    prizeAmount: 9750,
    hosterLiveRevenue: 1500,
    winnerFolio: "HL-052",
    status: "active",
    durationMinutes: 7,
  },
  {
    id: "session-007",
    restaurantName: "Rancho Viejo",
    restaurantId: "rancho-viejo",
    date: "2026-05-20",
    time: "23:04",
    mode: "Centro 4",
    activeTables: 30,
    tablePrice: 100,
    grossRevenue: 3000,
    commissionPercent: 20,
    restaurantCommission: 600,
    prizeAmount: 2100,
    hosterLiveRevenue: 300,
    winnerFolio: "HL-017",
    status: "completed",
    durationMinutes: 11,
  },
  {
    id: "session-008",
    restaurantName: "Casa Norte",
    restaurantId: "casa-norte",
    date: "2026-05-20",
    time: "22:12",
    mode: "Figura X",
    activeTables: 30,
    tablePrice: 200,
    grossRevenue: 6000,
    commissionPercent: 24,
    restaurantCommission: 1440,
    prizeAmount: 3960,
    hosterLiveRevenue: 600,
    winnerFolio: "HL-031",
    status: "cancelled",
    durationMinutes: 4,
  },
];
